# Generated by Django 4.2.4 on 2023-09-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_anb', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('hierarchy', models.CharField(choices=[('Ex-aluna', 'Ex-aluna'), ('Homenageado', 'Homenageado'), ('Homenageada', 'Homenageada'), ('Moradora', 'Moradora'), ('Agregada', 'Agregada'), ('Pseudo-morador', 'Pseudo-morador'), ('Bixo', 'Bixo')], max_length=15)),
                ('course', models.CharField(default='', max_length=100)),
                ('tentos', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
