# Generated by Django 4.2.4 on 2023-09-04 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_anb', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giver', to='site_anb.userprofile')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='site_anb.userprofile')),
            ],
        ),
    ]
