# Generated by Django 4.2.4 on 2023-09-05 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_anb', '0007_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('cpf', models.CharField(max_length=12)),
                ('cellphone_number', models.CharField(max_length=30)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('regular_medicines', models.CharField(blank=True, default='Nenhum', max_length=100, null=True)),
                ('past_medicines', models.CharField(blank=True, default='Nenhum', max_length=100, null=True)),
                ('broken_bones', models.CharField(blank=True, default='Nenhum', max_length=100, null=True)),
                ('allergies', models.CharField(blank=True, default='Nenhum', max_length=100, null=True)),
                ('diseases', models.CharField(blank=True, default='Nenhum', max_length=200, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_anb.address')),
                ('emergency_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_anb.emergencycontact')),
            ],
        ),
    ]
