# Generated by Django 4.2.4 on 2023-09-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_anb', '0008_medicalpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tento',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
